sudo: required

language: python

python:
  - "3.6"

services:
  - docker

git:
  depth: 1

branches:
  only:
    - master

env:
  global:
    # Variables found by default in Docker Hub builder
    - DOCKER_REPO=tecnativa/odoo-base
    - DOCKER_TAG=latest
    - IMAGE_NAME=$DOCKER_REPO:$DOCKER_TAG

before_install:
  - docker version
  - docker info
  - ./hooks/build

install:
  - pip install -r requirements-ci.txt

script:
  - python -m unittest -v tests
